apiVersion: v1
kind: Service
metadata:
  name: {{ include "nti-frontend.serviceName" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ include "nti-frontend.name" . }}